# Generated by Django 2.1.7 on 2019-09-12 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170831_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('primary', models.BooleanField(default=False)),
                ('verification_key', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30, unique=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=100, null=True)),
                ('gravatar_id', models.CharField(blank=True, max_length=100, null=True)),
                ('html_url', models.URLField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('node_id', models.CharField(default='', max_length=50, unique=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('followers_url', models.URLField(blank=True, max_length=100, null=True)),
                ('following_url', models.URLField(blank=True, max_length=100, null=True)),
                ('gists_url', models.URLField(blank=True, max_length=100, null=True)),
                ('starred_url', models.URLField(blank=True, max_length=100, null=True)),
                ('subscriptions_url', models.URLField(blank=True, max_length=100, null=True)),
                ('organizations_url', models.URLField(blank=True, max_length=100, null=True)),
                ('repos_url', models.URLField(blank=True, max_length=100, null=True)),
                ('events_url', models.URLField(blank=True, max_length=100, null=True)),
                ('received_events_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='html_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='githubuserinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_user_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountmergerequest',
            name='master_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_merge_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountmergerequest',
            name='secondary_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_merge_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accountmergerequest',
            unique_together={('master_account', 'secondary_account')},
        ),
    ]
