# Generated by Django 2.1.7 on 2019-09-05 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190830_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmergerequest',
            name='master_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_merge_requests', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AlterField(
            model_name='accountmergerequest',
            name='secondary_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_merge_requests', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
