# Generated by Django 2.1.7 on 2019-09-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_auto_20181218_1934'),
        ('profiles', '0008_auto_20190912_1800'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('remote_id', 'producer')},
        ),
    ]
