# Generated by Django 2.1.7 on 2019-09-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190913_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scrubbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
