# Generated by Django 2.1.5 on 2019-03-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_linkedinuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='profiles.LinkedInUserInfo'),
        ),
    ]
