# Generated by Django 2.1.7 on 2019-09-20 22:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190917_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmergerequest',
            old_name='key',
            new_name='master_key',
        ),
        migrations.AddField(
            model_name='accountmergerequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountmergerequest',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountmergerequest',
            name='master_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountmergerequest',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='accountmergerequest',
            name='secondary_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountmergerequest',
            name='secondary_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='accountmergerequest',
            name='master_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_merge_requests', to='profiles.EmailAddress'),
        ),
        migrations.AlterField(
            model_name='accountmergerequest',
            name='secondary_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_merge_requests', to='profiles.EmailAddress'),
        ),
    ]
