# Generated by Django 2.1.5 on 2019-03-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_user_linkedin_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockeruserinfo',
            old_name='docker_uid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='githubuserinfo',
            old_name='github_uid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='linkedinuserinfo',
            old_name='linkedin_uid',
            new_name='uid',
        ),
    ]
