# Generated by Django 2.1.5 on 2019-04-23 18:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_auto_20181218_1934'),
        ('profiles', '0012_auto_20190328_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='producers.Producer')),
            ],
        ),
    ]
