# Generated by Django 2.1.5 on 2019-04-24 20:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_auto_20181218_1934'),
        ('profiles', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('remote_id', 'producer')},
        ),
    ]
