# Generated by Django 2.1.7 on 2019-04-29 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20190425_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=150),
        ),
    ]
