# Generated by Django 2.1.7 on 2019-05-14 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('master_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_merge_requests', to=settings.AUTH_USER_MODEL)),
                ('secondary_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_merge_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accountmergerequest',
            unique_together={('master_account', 'secondary_account')},
        ),
    ]
