#machine:
#  python:
#    version: 3.6.1
#
#dependencies:
#  pre:
#    - pip install -r requirements.dev.txt
#
#test:
#  override:
#    - python manage.py test
#    - flake8 src/ --ignore E501
#
#    # Check templates and such for style= attributes
#    - if [[ `grep -rnw src/templates/ -e 'style='` ]]; then (exit -1); fi
#    - if [[ `grep -rnw src/static/riot -e 'style='` ]]; then (exit -1); fi
#    - if [[ `grep -rnw src -e 'TODO'` ]]; then (exit -1); fi

version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout
      - restore_cache:
          key: chahub-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
      - run: sudo pip install -r requirements.dev.txt
      - save_cache:
          key: codalab-{{ .Branch }}-{{ checksum "codalab/requirements/common.txt" }}
          paths:
          - "~/.cache/pip"
      - run: py.test
      - run: flake8 src/ --ignore E501

workflows:
  version: 2
  build_and_test:
    jobs:
      - test