version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6-jessie-browsers
      - image: library/elasticsearch:5.6
    steps:
      - checkout
      - run: sudo pip install -r requirements.dev.txt
      - run: mkdir -p src/static/generated/
      - run: python manage.py collectstatic --no-input
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash - && sudo apt install nodejs && sudo npm install riot -g riot-compiler --save stylus -g
      - run: riot src/static/riot src/static/generated/riot.js --style stylus
      - run: stylus --compress --sourcemap-inline < src/static/stylus/index.styl > src/static/generated/output.css
      - run: python manage.py migrate
      - run: python manage.py create_competition --amount 3 --fill-all-details True --fail-on-exception True
      - run: echo "Y" | python manage.py search_index --rebuild
      - run: mkdir artifacts/
      - save_cache:
          key: codalab-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
          paths:
            - ~/.cache/pip
      - run: py.test
      - store_artifacts:
          path: artifacts/
      - run: 'flake8 src/ --ignore E501'
#      - run: if [[ `grep -rnw src -e 'TODO'` ]]; then (exit -1); fi
#      - run [[ `grep -rnw src/templates/ -e 'style='` ]]; then (exit -1); fi
#      - run [[ `grep -rnw src/static/riot -e 'style='` ]]; then (exit -1); fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
