version: '2'
services:
  #-----------------------------------------------
  #   Web Service
  #-----------------------------------------------
  django:
    build: .
    container_name: django
    hostname: django
    command: bash -c "cd /app/src && /usr/local/bin/gunicorn asgi:application -w 2 -k uvicorn.workers.UvicornWorker -b :8000 -b :80 --reload"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.base
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    env_file: .env
    volumes:
      - .:/app
      - /tmp/codalab-v2/django:/codalab_tmp
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - postgres
      - elastic-search
    stdin_open: true
    tty: true
    logging:
      options:
        max-size: "500k"
        max-file: "10"
  # --------------------------------------------------------------------------
  # Database
  # --------------------------------------------------------------------------
  postgres:
    image: postgres:9.6.3
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${LOGGING_DIR}/psql:/var/log/psql
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
      - ./backups:/app/backups
    env_file: .env
    logging:
      options:
        max-size: "200k"
    container_name: postgres-chahub
  # --------------------------------------------------------------------------
  # Elastic Search
  # --------------------------------------------------------------------------
  elastic-search:
    image: elasticsearch:6.6.0
    hostname: elastic-search
    restart: unless-stopped
    ports:
      - 9200:9200
    env_file: .env
    logging:
      options:
        max-size: "200k"
    container_name: elastic-search
  #-----------------------------------------------
  #   Local development helper, rebuilds RiotJS/Stylus on change
  #-----------------------------------------------
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - .:/app
    logging:
      options:
        max-size: "500k"
        max-file: "10"
