version: '3'
services:
  #-----------------------------------------------
  #   Web Service
  #-----------------------------------------------
  django:
    build: .
    command: bash -c "cd /app/src && watchmedo auto-restart -p '*.py' --recursive -- gunicorn asgi:application -w 2 -k uvicorn.workers.UvicornWorker -b :8888"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.base
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    env_file: .env
    volumes:
      - .:/app
      - /tmp/codalab-v2/django:/codalab_tmp
    ports:
      - 8888:8888
    depends_on:
      - postgres
      - elasticsearch
      - rabbit
    stdin_open: true
    tty: true
    logging:
      options:
        max-size: "20k"
        max-file: "10"

  # --------------------------------------------------------------------------
  # Database
  # --------------------------------------------------------------------------
  postgres:
    image: postgres:9.6.15
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${LOGGING_DIR}/psql:/var/log/psql
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
      - ./backups:/app/backups
    env_file: .env
    logging:
      options:
        max-size: "20k"

  # --------------------------------------------------------------------------
  # Elastic Search
  # --------------------------------------------------------------------------
  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
      - 9200:9200
    volumes:
      - ./var/data/elasticsearch:/usr/share/elasticsearch/data
    env_file: .env
    logging:
      options:
        max-size: "20k"

  #-----------------------------------------------
  #   Rabbitmq Service
  #-----------------------------------------------
  rabbit:
    image: rabbitmq:3.8-management
    env_file: .env
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      # To save rabbit state between container ups/downs
      - ./var/rabbit:/var/lib/rabbit/:delegated
    logging:
      options:
        max-size: "20k"
        max-file: "10"

  #-----------------------------------------------
  #   Celery Service
  #-----------------------------------------------
  site_worker:
    command: bash -c "watchmedo auto-restart -p '*.py' --recursive -- celery -A celery_config worker -Q site-worker -l info -n site-worker@%n"
    working_dir: /app/src
    build:
      context: .
    depends_on:
      - rabbit
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=settings.base
    env_file: .env
    volumes:
      - .:/app
    logging:
      options:
        max-size: "20k"
        max-file: "10"

  #-----------------------------------------------
  #   Local development helper, rebuilds RiotJS/Stylus on change
  #-----------------------------------------------
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - .:/app
    logging:
      options:
        max-size: "20k"
        max-file: "10"
