# Generated by Django 2.1.11 on 2019-10-18 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='key',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='task',
            name='key',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
