# Generated by Django 2.1.11 on 2019-12-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='tasks',
        ),
        migrations.AddField(
            model_name='solution',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='solutions', to='tasks.Task'),
        ),
    ]
