# Generated by Django 2.1.7 on 2019-08-23 21:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_auto_20181218_1934'),
        ('tasks', '0003_auto_20190430_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='key',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='task',
            name='key',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('producer', 'remote_id', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('producer', 'remote_id', 'key')},
        ),
    ]
