# Generated by Django 2.0 on 2017-12-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.UUIDField()),
                ('name', models.TextField()),
                ('contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
