# Generated by Django 2.1.2 on 2018-12-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_auto_20180202_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='competition_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producer',
            name='dataset_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producer',
            name='organizer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producer',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producer',
            name='submission_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producer',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
