# Generated by Django 2.1.11 on 2019-12-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_auto_20181218_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='competition_count',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='dataset_count',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='organizer_count',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='submission_count',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='user_count',
        ),
    ]
