# Generated by Django 2.0 on 2017-12-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20171222_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='remote_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
