# Generated by Django 2.0 on 2018-02-02 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20171222_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='url',
            field=models.URLField(default='http://localhost/yaaaaaaaa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='index',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 3, 49, 56, 994174, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_by',
            field=models.TextField(default=datetime.datetime(2018, 2, 2, 3, 50, 11, 47208, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
