# Generated by Django 2.0 on 2018-02-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_competition_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
