# Generated by Django 2.0 on 2018-02-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20180215_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='competitions.CompetitionParticipant'),
        ),
    ]
