# Generated by Django 2.0 on 2018-02-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_competition_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='never_ends',
            field=models.BooleanField(default=False),
        ),
    ]
