# Generated by Django 2.0 on 2018-02-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_phase_never_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.TextField(),
        ),
    ]
