# Generated by Django 2.0 on 2018-02-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_auto_20180221_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
    ]
