# Generated by Django 2.0 on 2018-02-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_competition_participant_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
