# Generated by Django 2.0 on 2018-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_auto_20180226_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='html_data',
            field=models.TextField(default=''),
        ),
    ]
