# Generated by Django 2.0 on 2018-02-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_competition_html_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.URLField(default='/static/img/img-wireframe.png'),
        ),
    ]
