# Generated by Django 2.0 on 2018-03-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_auto_20180228_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='html_data',
            new_name='html_text',
        ),
    ]
