# Generated by Django 2.0 on 2018-03-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_competition_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to='competitions.CompetitionParticipant'),
        ),
    ]
