# Generated by Django 2.0 on 2018-03-09 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_auto_20180308_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='remote_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 6, 13, 43, 382205, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
