# Generated by Django 2.0 on 2018-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_auto_20180309_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='current_phase_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
