# Generated by Django 2.0 on 2018-03-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_auto_20180309_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.URLField(blank=True, default='/static/img/img-wireframe.png', null=True),
        ),
    ]
