# Generated by Django 2.0 on 2018-05-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_auto_20180320_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
