# Generated by Django 2.0 on 2018-03-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_auto_20180320_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='producer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='producers.Producer'),
            preserve_default=False,
        ),
    ]
