# Generated by Django 2.0 on 2018-06-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_competition_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='html_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
