# Generated by Django 2.0 on 2018-06-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_auto_20180606_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='remote_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
