# Generated by Django 2.0 on 2018-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_auto_20180613_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='remote_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
