# Generated by Django 2.0 on 2019-01-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_auto_20180815_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='logo',
            new_name='logo_url',
        ),
    ]
