# Generated by Django 2.1.11 on 2019-11-22 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_auto_20181218_1934'),
        ('competitions', '0032_auto_20190110_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_participants', to='producers.Producer'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='remote_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='remote_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
