# Generated by Django 2.1.7 on 2019-08-23 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0032_auto_20190110_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='profiles.Profile'),
        ),
    ]
