# Generated by Django 2.1.11 on 2019-12-03 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_auto_20191203_0054'),
        ('datasets', '0005_auto_20191122_0105'),
        ('tasks', '0002_auto_20191203_0054'),
        ('competitions', '0032_auto_20190110_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='participant',
        ),
        migrations.AddField(
            model_name='competition',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_participants', to='producers.Producer'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='remote_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='remote_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='phases', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='submission',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='submission',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='owner',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='producers.Producer'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='producers.Producer'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.Phase'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
