# Generated by Django 2.1.7 on 2019-08-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_auto_20190823_2124'),
        ('profiles', '0007_auto_20190823_2124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionparticipant',
            unique_together={('user', 'competition')},
        ),
    ]
