# Generated by Django 2.1.11 on 2019-10-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_auto_20191008_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.IntegerField(),
        ),
    ]
