# Generated by Django 2.1.11 on 2019-11-22 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('producers', '0003_auto_20181218_1934'),
        ('datasets', '0005_auto_20191122_0105'),
        ('competitions', '0033_auto_20191122_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='phases', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='submission',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='submission',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='producers.Producer'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='producers.Producer'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.Phase'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
