# Generated by Django 2.1.7 on 2019-04-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_competition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
