# Generated by Django 2.1.11 on 2019-12-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_auto_20191122_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='participant_count',
        ),
    ]
