# Generated by Django 2.1.5 on 2019-04-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_competition_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_competitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
