# Generated by Django 2.1.7 on 2019-07-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20190514_2153'),
        ('competitions', '0035_auto_20190430_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='user',
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='profiles.Profile'),
        ),
    ]
