# Generated by Django 2.1.11 on 2019-10-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('competitions', '0035_phase_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='phases', to='tasks.Task'),
        ),
    ]
