# Generated by Django 2.1.7 on 2019-07-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20190514_2153'),
        ('competitions', '0036_auto_20190723_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='profile',
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.Competition'),
        ),
    ]
