# Generated by Django 2.1.11 on 2019-10-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0036_phase_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
