# Generated by Django 2.1.7 on 2019-07-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20190514_2153'),
        ('competitions', '0037_auto_20190729_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionparticipant',
            unique_together={('user', 'competition')},
        ),
    ]
