# Generated by Django 2.1.11 on 2019-10-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0038_competitionparticipant_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipant',
            name='remote_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
