# Generated by Django 2.1.7 on 2019-08-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0038_auto_20190730_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='profiles.Profile'),
        ),
    ]
