# Generated by Django 2.1.11 on 2019-11-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_competitionparticipant_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
